In [24]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
from matplotlib.pyplot import *

In [9]:
df = pd.read_excel("/content/MBTIx.xlsx")



In [10]:
df.head()

type                                              posts
0  INFJ  http://www.youtube.com/watch?v=qsXHcwe3krw|||h...
1  ENTP  I'm finding the lack of me in these posts very...
2  INTP  Good one  _____   https://www.youtube.com/watc...
3  INTJ  Dear INTP,   I enjoyed our conversation the ot...
4  ENTJ  You're fired.|||That's another silly misconcep...

In [11]:
df.describe()

type                                              posts
count   8675                                               8675
unique    16                                               8675
top     INFP  http://www.youtube.com/watch?v=qsXHcwe3krw|||h...
freq    1832                                                  1

In [12]:
[p.split('|||') for p in df .head(1).posts.values]


[['http://www.youtube.com/watch?v=qsXHcwe3krw',
  'http://41.media.tumblr.com/tumblr_lfouy03PMA1qa1rooo1_500.jpg',
  'enfp and intj moments  https://www.youtube.com/watch?v=iz7lE1g4XM4  sportscenter not top ten plays  https://www.youtube.com/watch?v=uCdfze1etec  pranks',
  'What has been the most life-changing experience in your life?',
  'http://www.youtube.com/watch?v=vXZeYwwRDw8   http://www.youtube.com/watch?v=u8ejam5DP3E  On repeat for most of today.',
  'May the PerC Experience immerse you.',
  'The last thing my INFJ friend posted on his facebook before committing suicide the next day. Rest in peace~   http://vimeo.com/22842206',
  "Hello ENFJ7. Sorry to hear of your distress. It's only natural for a relationship to not be perfection all the time in every moment of existence. Try to figure the hard times as times of growth, as...",
  '84389  84390  http://wallpaperpassion.com/upload/23700/friendship-boy-and-girl-wallpaper.jpg  http://assets.dornob.com/wp-content/uploads/2010/04/

In [13]:
from sklearn.preprocessing import LabelEncoder

unique_type_list = ['INFJ', 'ENTP', 'INTP', 'INTJ', 'ENTJ', 'ENFJ', 'INFP', 'ENFP','ISFP', 'ISTP', 'ISFJ', 'ISTJ', 'ESTP', 'ESFP', 'ESTJ', 'ESFJ']
lab_encoder = LabelEncoder().fit(unique_type_list)

In [19]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [15]:
import time
import re

# Time
%time df.posts[1].replace('+', ' ').replace('.', ' ').replace(',', ' ').replace(':', ' ')
%time re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', df.posts[1])


from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Lemmatizer | Stemmatizer
stemmer = PorterStemmer()
lemmatiser = WordNetLemmatizer()

# Cache the stop words for speed
cachedStopWords = stopwords.words("english")
OnePost = df.posts[1]

# List all urls
urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', OnePost)

# Remove urls
temp = re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', 'link', OnePost)

# Keep only words
temp = re.sub("[^a-zA-Z]", " ", temp)

# Remove spaces > 1
temp = re.sub(' +', ' ', temp).lower()

# Remove stopwords and lematize
%time stemmer.stem(" ".join([w for w in temp.split(' ') if w not in cachedStopWords]))
print("\nBefore preprocessing:\n\n", OnePost[0:500])
print("\nAfter preprocessing:\n\n", temp[0:500])
print("\nList of urls:")
urls

CPU times: user 189 µs, sys: 0 ns, total: 189 µs
Wall time: 196 µs
CPU times: user 731 µs, sys: 0 ns, total: 731 µs
Wall time: 740 µs
CPU times: user 3.74 ms, sys: 0 ns, total: 3.74 ms
Wall time: 6.67 ms

Before preprocessing:

 I'm finding the lack of me in these posts very alarming.|||Sex can be boring if it's in the same position often. For example me and my girlfriend are currently in an environment where we have to creatively use cowgirl and missionary. There isn't enough...|||Giving new meaning to 'Game' theory.|||Hello *ENTP Grin*  That's all it takes. Than we converse and they do most of the flirting while I acknowledge their presence and return their words with smooth wordplay and more cheeky grins.|||This + La

After preprocessing:

 i m finding the lack of me in these posts very alarming sex can be boring if it s in the same position often for example me and my girlfriend are currently in an environment where we have to creatively use cowgirl and missionary there isn t enoug

['http://img188.imageshack.us/img188/6422/6020d1f9da6944a6b71bbe6.jpg',
 'http://img.adultdvdtalk.com/813a0c6243814cab84c51',
 'http://i817.photobucket.com/albums/zz96/kamioo/Dirtywinch.png',
 'http://i817.photobucket.com/albums/zz96/kamioo/Thunderstorm.pnghttp://i817.photobucket.com/albums/zz96/kamioo/Thunderstormbw.png',
 'http://i817.photobucket.com/albums/zz96/kamioo/Cosmicstorm.png',
 'http://www.youtube.com/watch?v=j5W73HaVQBg',
 'http://i817.photobucket.com/albums/zz96/kamioo/Deathgrip.png',
 'http://i817.photobucket.com/albums/zz96/kamioo/Deathgripbw.png',
 'http://i817.photobucket.com/albums/zz96/kamioo/Statickitten.png']

In [20]:
##### Compute list of subject with Type | list of comments
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Lemmatize
stemmer = PorterStemmer()
lemmatiser = WordNetLemmatizer()

def pre_process_data(data, remove_stop_words=True):

    list_personality = []
    list_posts = []
    len_data = len(data)
    i=0

    for row in data.iterrows():
        i+=1
        if i % 500 == 0:
            print("%s | %s rows" % (i, len_data))

        ##### Remove and clean comments
        posts = row[1].posts
        temp = re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', 'link', posts)
        temp = re.sub("[^a-zA-Z]", " ", temp)
        temp = re.sub(' +', ' ', temp).lower()
        if remove_stop_words:
            temp = " ".join([lemmatiser.lemmatize(w) for w in temp.split(' ') if w not in cachedStopWords])
        else:
            temp = " ".join([lemmatiser.lemmatize(w) for w in temp.split(' ')])

        type_labelized = lab_encoder.transform([row[1].type])[0]
        list_personality.append(type_labelized)
        list_posts.append(temp)

    #del data
    list_posts = np.array(list_posts)
    list_personality = np.array(list_personality)
    return list_posts, list_personality

list_posts, list_personality = pre_process_data(df, remove_stop_words=True)

500 | 8675 rows
1000 | 8675 rows
1500 | 8675 rows
2000 | 8675 rows
2500 | 8675 rows
3000 | 8675 rows
3500 | 8675 rows
4000 | 8675 rows
4500 | 8675 rows
5000 | 8675 rows
5500 | 8675 rows
6000 | 8675 rows
6500 | 8675 rows
7000 | 8675 rows
7500 | 8675 rows
8000 | 8675 rows
8500 | 8675 rows


In [21]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE

cntizer = CountVectorizer(analyzer="word",
                             max_features=1500,
                             tokenizer=None,
                             preprocessor=None,
                             stop_words=None,
#                             ngram_range=(1,1),
                             max_df=0.5,
                             min_df=0.1)

tfizer = TfidfTransformer()

print("CountVectorizer")
X_cnt = cntizer.fit_transform(list_posts)
print("Tf-idf")
X_tfidf =  tfizer.fit_transform(X_cnt).toarray()

CountVectorizer
Tf-idf


In [22]:
list_posts[0]

'link link enfp intj moment link sportscenter top ten play link prank life changing experience life link link repeat today may perc experience immerse last thing infj friend posted facebook committing suicide next day rest peace link hello enfj sorry hear distress natural relationship perfection time every moment existence try figure hard time time growth link link welcome stuff link game set match prozac wellbrutin least thirty minute moving leg mean moving sitting desk chair weed moderation maybe try edible healthier alternative basically come three item determined type whichever type want would likely use given type cognitive function whatnot left thing moderation sims indeed video game good one note good one somewhat subjective completely promoting death given sim dear enfp favorite video game growing current favorite video game cool link appears late sad someone everyone wait thought confidence good thing cherish time solitude b c revel within inner world whereas time workin enjoy

In [25]:
# Confusion plot
from sklearn.metrics import confusion_matrix
import itertools

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [27]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.feature_extraction.text import CountVectorizer

# Vectorizer
cntizer = CountVectorizer(analyzer="word",
                          max_features=1000,
                          tokenizer=None,
                          preprocessor=None,
                          stop_words=None,
                          max_df=0.5,
                          min_df=0.1)

# Multinomial Naive Bayes
mlNB = MultinomialNB()

def train_multinomialNB(X, y, nsplits=5):
    kf = StratifiedShuffleSplit(n_splits=nsplits)
    scores = []

    for train, test in kf.split(X, y):
        X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]

        X_train = cntizer.fit_transform(X_train)
        X_test = cntizer.transform(X_test)

        mlNB.fit(X_train, y_train)
        preds = mlNB.predict(X_test)

        score = f1_score(y_test, preds, average='weighted')
        scores.append(score)
        print('F1-score: %s' % score)

    avg_score = sum(scores) / len(scores)
    print('Average F1-score: %s' % avg_score)

# Replace 'list_posts' and 'list_personality' with your actual data
train_multinomialNB(list_posts, list_personality, nsplits=5)


F1-score: 0.622921763181865
F1-score: 0.6043155610811327
F1-score: 0.5949670481691847
F1-score: 0.5999208276021004
F1-score: 0.5847960544679766
Average F1-score: 0.6013842509004519


In [29]:
!pip install keras tensorflow


In [32]:
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, Bidirectional
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

# Tokenize
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(list_posts)
sequences = tokenizer.texts_to_sequences(list_posts)

word_index = tokenizer.word_index

# Convert personality labels to categorical
y_categorical = to_categorical(list_personality_bin)

# split the data into a training set and a validation set
x_train, x_val, y_train, y_val = train_test_split(sequences, y_categorical, test_size=0.3, random_state=0, stratify=y_categorical)

# truncate and pad input sequences
max_sequence_length = 600
X_train = pad_sequences(x_train, maxlen=max_sequence_length)
X_val = pad_sequences(x_val, maxlen=max_sequence_length)

max_features = 2000
batch_size = 32

model = Sequential()
model.add(Embedding(max_features, 256, input_length=max_sequence_length))
model.add(Bidirectional(LSTM(64)))
model.add(Dense(4, activation='softmax'))
model.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])

print('Train...')
model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=4,
          validation_data=(X_val, y_val))


NameError: ignored

In [39]:
# Split mbti personality into 4 letters and binarize
titles = ["Extraversion (E) - Introversion (I)",
          "Sensation (S) - INtuition (N)",
          "Thinking (T) - Feeling (F)",
          "Judgement (J) - Perception (P)"
         ]
b_Pers = {'I':0, 'E':1, 'N':0, 'S':1, 'F':0, 'T':1, 'J':0, 'P':1}
b_Pers_list = [{0:'I', 1:'E'}, {0:'N', 1:'S'}, {0:'F', 1:'T'}, {0:'J', 1:'P'}]

def translate_personality(personality):
    '''
    transform mbti to binary vector
    '''
    return [b_Pers[l] for l in personality]

def translate_back(personality):
    '''
    transform binary vector to mbti personality
    '''
    s = ""
    for i, l in enumerate(personality):
        s += b_Pers_list[i][l]
    return s

list_personality_bin = np.array([translate_personality(p) for p in df.type])
print("Binarize MBTI list: \n%s" % list_personality_bin)


Binarize MBTI list: 
[[0 0 0 0]
 [1 0 1 1]
 [0 0 1 1]
 ...
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 1]]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, Bidirectional
from keras.preprocessing import sequence
from sklearn.model_selection import train_test_split
from keras.utils import pad_sequences

# Constants
MAX_NB_WORDS = 20000  # Adjust this according to your data
max_sentence_length = 600  # Adjust this according to your data
max_features = 2000
batch_size = 32

# Tokenize and preprocess data
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(list_posts)
sequences = tokenizer.texts_to_sequences(list_posts)
X =pad_sequences(sequences, maxlen=max_sentence_length)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, list_personality_bin, test_size=0.3, random_state=0, stratify=list_personality_bin)

# Build and compile the bidirectional LSTM model
model = Sequential()
model.add(Embedding(max_features, 256, input_length=max_sentence_length))
model.add(Bidirectional(LSTM(64)))
model.add(Dense(4, activation='softmax'))
model.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=4,
          validation_data=(X_test, y_test))
